"""
錯誤碼整數定義與對應中文訊息
"""

class ResultCode:
    SUCCESS = 0
    TESTDATA_GENERATION_SUCCESS = 10000  # 測資任務完成的特殊成功碼

    # 工具模組區錯誤碼
    FILE_SERIALIZATION_FAILED = 80101
    FILE_WRITE_FAILED = 80102
    INVALID_FILE_KIND = 80103
    UUID_FORMAT_INVALID = 80104
    USER_TESTDATA_ALREADY_EXISTS = 80105

    INVALID_DATA_TYPE = 80201
    ENRICH_UUID_FAILED = 80202

    USER_TESTDATA_FILE_WRITE_FAILED = 80301

    FILE_NOT_FOUND = 80401
    INVALID_FILE_DATA = 80402
    FILE_LOAD_FAILED = 80403
    FILE_PERMISSION_DENIED = 80404
    UNKNOWN_FILE_SAVE_ERROR = 80405

    UUID_GEN_FAIL = 80501

    # 任務模組區錯誤碼
    FAKER_GENERATE_FAILED = 20101
    USER_GENERATOR_SAVE_FAILED = 20102

    PRODUCT_CATEGORY_EMPTY = 20201
    PRODUCT_GENERATION_FAILED = 20202
    PRODUCT_GENERATOR_SAVE_FAILED = 20203


# 代表成功的錯誤碼整數集合
SUCCESS_CODES = {
    ResultCode.SUCCESS,
    ResultCode.TESTDATA_GENERATION_SUCCESS,
}

ERROR_CODE_MSG_MAP = {
    ResultCode.SUCCESS: "成功",
    ResultCode.TESTDATA_GENERATION_SUCCESS: "測資任務完成",

    ResultCode.FILE_SERIALIZATION_FAILED: "檔案序列化失敗",
    ResultCode.FILE_WRITE_FAILED: "檔案寫入失敗",
    ResultCode.INVALID_FILE_KIND: "無效的檔案類型",
    ResultCode.UUID_FORMAT_INVALID: "UUID 格式錯誤",
    ResultCode.USER_TESTDATA_ALREADY_EXISTS: "使用者測資檔案已存在",

    ResultCode.INVALID_DATA_TYPE: "資料型別錯誤，非字典格式",
    ResultCode.ENRICH_UUID_FAILED: "資料 enrich UUID 失敗",

    ResultCode.USER_TESTDATA_FILE_WRITE_FAILED: "使用者測資檔案寫入失敗",

    ResultCode.FILE_NOT_FOUND: "檔案不存在",
    ResultCode.INVALID_FILE_DATA: "檔案內容空或格式錯誤",
    ResultCode.FILE_LOAD_FAILED: "讀取檔案失敗",
    ResultCode.FILE_PERMISSION_DENIED: "檔案權限不足",
    ResultCode.UNKNOWN_FILE_SAVE_ERROR: "不明的檔案儲存錯誤",

    ResultCode.UUID_GEN_FAIL: "UUID 產生失敗",

    ResultCode.FAKER_GENERATE_FAILED: "假資料產生失敗",
    ResultCode.USER_GENERATOR_SAVE_FAILED: "使用者測資寫入失敗",

    ResultCode.PRODUCT_CATEGORY_EMPTY: "商品分類為空",
    ResultCode.PRODUCT_GENERATION_FAILED: "商品產生失敗",
    ResultCode.PRODUCT_GENERATOR_SAVE_FAILED: "商品測資寫入失敗",
}
